using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Server.Models;
using Server.Services;
using System.Security.Claims;
using System.Text;

namespace Server.Controllers;

[ApiController]
[Route("api/[controller]")]
public class VideosController : ControllerBase
{
    private readonly IVideoService _videoService;
    private readonly IConfiguration _configuration;
    private readonly IWebHostEnvironment _environment;
    private static readonly byte[] PlaceholderPreviewBytes = Convert.FromBase64String(
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7Z3ioAAAAASUVORK5CYII="
    );
    
    public VideosController(IVideoService videoService, IConfiguration configuration, IWebHostEnvironment environment)
    {
        _videoService = videoService;
        _configuration = configuration;
        _environment = environment;
    }

    private string ResolveUploadsPath()
    {
        var configured = _configuration["UploadsPath"] ?? "uploads";
        return Path.IsPathRooted(configured)
            ? configured
            : Path.GetFullPath(Path.Combine(_environment.ContentRootPath, configured));
    }
    
    [HttpGet]
    public async Task<IActionResult> GetVideos([FromQuery] string? search, [FromQuery] string? category)
    {
        var videos = await _videoService.GetAllVideosAsync(search, category);
        return Ok(videos);
    }
    
    [HttpGet("{id}")]
    public async Task<IActionResult> GetVideo(Guid id)
    {
        var video = await _videoService.GetVideoByIdAsync(id);
        if (video == null) return NotFound();
        
        // Просмотров не увеличиваем здесь - только при реальном просмотре
        return Ok(video);
    }
    
    [HttpGet("{id}/preview")]
    public async Task<IActionResult> GetPreview(Guid id)
    {
        var video = await _videoService.GetVideoByIdAsync(id);
        if (video == null) return NotFound();
        
        var uploadsPath = ResolveUploadsPath();
        var videoFolder = Path.Combine(uploadsPath, id.ToString());
        var previewPath = Path.Combine(videoFolder, "preview.jpg");

        if (!System.IO.File.Exists(previewPath) && Directory.Exists(videoFolder))
        {
            var candidates = Directory.GetFiles(videoFolder, "preview.*");
            if (candidates.Length > 0)
            {
                previewPath = candidates[0];
            }
        }
        
        if (!System.IO.File.Exists(previewPath))
        {
            return File(PlaceholderPreviewBytes, "image/png");
        }
        
        var fileBytes = await System.IO.File.ReadAllBytesAsync(previewPath);
        var ext = Path.GetExtension(previewPath).ToLowerInvariant();
        var mimeType = ext switch
        {
            ".png" => "image/png",
            ".webp" => "image/webp",
            _ => "image/jpeg"
        };

        return File(fileBytes, mimeType);
    }
    
    [HttpGet("{id}/stream")]
    public async Task<IActionResult> StreamVideo(Guid id)
    {
        try
        {
            var hlsPath = await _videoService.GetVideoStreamPathAsync(id);
            
            // Просмотров не увеличиваем здесь - только при реальном просмотре через /watch endpoint
            
            // HLS playlists generated by ffmpeg typically reference segments with relative paths like `playlist0.ts`.
            // Clients often fetch the playlist from a URL like `/api/videos/{id}/stream` (no trailing slash).
            // RFC3986 relative resolution then points segments at `/api/videos/{id}/playlist0.ts`, but this API serves
            // segments at `/api/videos/{id}/stream/{segment}` — resulting in 404s and "black screen" in embedded players.
            //
            // Fix: rewrite relative segment lines to absolute URLs under `/api/videos/{id}/stream/`.
            var playlistText = await System.IO.File.ReadAllTextAsync(hlsPath);
            var rewritten = RewriteHlsPlaylistForStreamEndpoint(playlistText, Request, id);
            return Content(rewritten, "application/vnd.apple.mpegurl", Encoding.UTF8);
        }
        catch (FileNotFoundException)
        {
            return NotFound();
        }
    }
    
    [HttpPost("{id}/view")]
    public async Task<IActionResult> RecordView(Guid id)
    {
        var video = await _videoService.GetVideoByIdAsync(id);
        if (video == null) return NotFound();
        
        try
        {
            await _videoService.IncrementViewsAsync(id);
            return Ok(new { success = true });
        }
        catch
        {
            return Ok(new { success = false });
        }
    }

    // Simple HTML watch page (works anywhere a browser works).
    // Note: kept under /api for convenience; can be moved to a dedicated controller later.
    [HttpGet("{id}/watch")]
	public async Task<IActionResult> Watch(Guid id)
	{
	    var video = await _videoService.GetVideoByIdAsync(id);
	    if (video == null) return NotFound();

	    // Просмотров не увеличиваем здесь - клиент сам вызовет /view при начале воспроизведения

        var streamUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/api/videos/{id}/stream";
        var viewUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}/api/videos/{id}/view";

        var html = $@"<!doctype html>
<html>
<head>
  <meta charset=""utf-8"" />
  <meta name=""viewport"" content=""width=device-width, initial-scale=1"" />
  <title>{System.Net.WebUtility.HtmlEncode(video.Title)}</title>
  <style>
    html, body {{ height: 100%; margin: 0; background: #000; }}
    .wrap {{ height: 100%; display: flex; align-items: center; justify-content: center; }}
    video {{ width: 100%; height: 100%; max-width: 100%; max-height: 100%; background: #000; }}
  </style>
  <script src=""https://cdn.jsdelivr.net/npm/hls.js@latest""></script>
</head>
<body>
  <div class=""wrap"">
    <video id=""v"" controls autoplay playsinline></video>
  </div>
  <script>
    const video = document.getElementById('v');
    const src = {System.Text.Json.JsonSerializer.Serialize(streamUrl)};
    const viewUrl = {System.Text.Json.JsonSerializer.Serialize(viewUrl)};
    let viewRecorded = false;
    
    function recordView() {{
      if (viewRecorded) return;
      viewRecorded = true;
      fetch(viewUrl, {{ method: 'POST' }}).catch(() => {{}});
    }}
    
    video.addEventListener('play', recordView, {{ once: true }});
    
    if (video.canPlayType('application/vnd.apple.mpegurl')) {{
      video.src = src;
    }} else if (window.Hls) {{
      const hls = new Hls({{ enableWorker: true, lowLatencyMode: true }});
      hls.loadSource(src);
      hls.attachMedia(video);
    }} else {{
      video.outerHTML = '<div style=""color:#fff;font-family:sans-serif;padding:16px"">HLS не поддерживается</div>';
    }}
  </script>
</body>
</html>";

        return Content(html, "text/html; charset=utf-8");
    }

    private static string RewriteHlsPlaylistForStreamEndpoint(string playlist, HttpRequest request, Guid videoId)
    {
        var baseUrl = $"{request.Scheme}://{request.Host}{request.PathBase}";
        var segmentPrefix = $"{baseUrl}/api/videos/{videoId}/stream/";

        var sb = new StringBuilder(capacity: Math.Max(playlist.Length, 256));
        using var reader = new StringReader(playlist);
        string? line;
        while ((line = reader.ReadLine()) != null)
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0 ||
                trimmed.StartsWith("#", StringComparison.Ordinal) ||
                trimmed.StartsWith("http://", StringComparison.OrdinalIgnoreCase) ||
                trimmed.StartsWith("https://", StringComparison.OrdinalIgnoreCase) ||
                trimmed.StartsWith("//", StringComparison.Ordinal))
            {
                sb.AppendLine(line);
                continue;
            }

            // If it's already an app-relative URL, leave it alone.
            if (trimmed.StartsWith('/'))
            {
                sb.AppendLine(line);
                continue;
            }

            var segmentName = trimmed;
            var absolute = $"{segmentPrefix}{segmentName}";
            sb.AppendLine(absolute);
        }

        return sb.ToString();
    }

    private string ResolveAuthoritativeFilePath(string? filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
        {
            return string.Empty;
        }

        if (Path.IsPathRooted(filePath))
        {
            return filePath;
        }

        return Path.GetFullPath(Path.Combine(_environment.ContentRootPath, filePath));
    }

    private bool CanPreviewNonPublicVideo(ClaimsPrincipal user, VideoDto video)
    {
        var role = user.FindFirstValue(ClaimTypes.Role);
        if (role == "moderator" || role == "admin")
        {
            return true;
        }

        var userIdClaim = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if (userIdClaim == null)
        {
            return false;
        }

        return Guid.TryParse(userIdClaim, out var userId) && userId == video.AuthorId;
    }

    // IMPORTANT: Must be registered before `{id}/{segment}` otherwise "playback" is treated as a segment name.
    [HttpGet("{id}/playback")]
    public async Task<IActionResult> GetPlayback(Guid id)
    {
        var video = await _videoService.GetVideoByIdAsync(id);
        if (video == null)
        {
            return NotFound();
        }

        var baseUrl = $"{Request.Scheme}://{Request.Host}{Request.PathBase}";

        // Published catalog videos: HLS only, anonymous OK.
        if (string.Equals(video.Status, "approved", StringComparison.OrdinalIgnoreCase))
        {
            return Ok(new VideoPlaybackDto($"{baseUrl}/api/videos/{id}/stream", "hls"));
        }

        if (!CanPreviewNonPublicVideo(User, video))
        {
            return Unauthorized();
        }

        var uploadsPath = ResolveUploadsPath();
        var hlsPath = Path.Combine(uploadsPath, id.ToString(), "playlist.m3u8");
        if (System.IO.File.Exists(hlsPath))
        {
            return Ok(new VideoPlaybackDto($"{baseUrl}/api/videos/{id}/stream", "hls"));
        }

        var originalDbPath = await _videoService.GetVideoOriginalPathAsync(id);
        var originalPath = ResolveAuthoritativeFilePath(originalDbPath);
        if (string.IsNullOrWhiteSpace(originalPath) || !System.IO.File.Exists(originalPath))
        {
            return NotFound();
        }

        return Ok(new VideoPlaybackDto($"{baseUrl}/api/videos/{id}/original", "file"));
    }

    [Authorize]
    [HttpGet("{id}/original")]
    public async Task<IActionResult> StreamOriginal(Guid id)
    {
        var video = await _videoService.GetVideoByIdAsync(id);
        if (video == null)
        {
            return NotFound();
        }

        if (!CanPreviewNonPublicVideo(User, video))
        {
            return Forbid();
        }

        var originalDbPath = await _videoService.GetVideoOriginalPathAsync(id);
        var path = ResolveAuthoritativeFilePath(originalDbPath);
        if (string.IsNullOrWhiteSpace(path) || !System.IO.File.Exists(path))
        {
            return NotFound();
        }

        var ext = Path.GetExtension(path).ToLowerInvariant();
        var mime = ext switch
        {
            ".mp4" => "video/mp4",
            ".webm" => "video/webm",
            ".mkv" => "video/x-matroska",
            ".mov" => "video/quicktime",
            _ => "application/octet-stream"
        };

        var fileBytes = await System.IO.File.ReadAllBytesAsync(path);
        return File(fileBytes, mime);
    }
    
    [HttpGet("{id}/stream/{segment}")]
    public async Task<IActionResult> GetSegment(Guid id, string segment)
    {
        try
        {
            var video = await _videoService.GetVideoByIdAsync(id);
            if (video == null) return NotFound();
            
            var uploadsPath = ResolveUploadsPath();
            var segmentPath = Path.Combine(uploadsPath, id.ToString(), segment);
            
            if (!System.IO.File.Exists(segmentPath))
                return NotFound();
            
            var fileBytes = await System.IO.File.ReadAllBytesAsync(segmentPath);
            return File(fileBytes, "video/MP2T");
        }
        catch
        {
            return NotFound();
        }
    }

    [HttpGet("{id}/{segment}")]
    public async Task<IActionResult> GetSegmentFromRoot(Guid id, string segment)
    {
        return await GetSegment(id, segment);
    }
    
    [Authorize]
    [HttpPost]
    [RequestSizeLimit(2L * 1024 * 1024 * 1024)]
    [RequestFormLimits(MultipartBodyLengthLimit = 2L * 1024 * 1024 * 1024)]
    public async Task<IActionResult> UploadVideo([FromForm] VideoUploadRequest request)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null) return Unauthorized();
        
        var userId = Guid.Parse(userIdClaim);
        var uploadsPath = ResolveUploadsPath();
        
        Directory.CreateDirectory(uploadsPath);
        
        var result = await _videoService.UploadVideoAsync(
            userId,
            new VideoCreateRequest(request.Title, request.Description, request.Category, request.Tags ?? new List<string>()),
            request.File,
            request.PreviewFile,
            uploadsPath
        );
        
        return Ok(result);
    }
    
    [Authorize]
    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateVideo(Guid id, [FromBody] VideoUpdateRequest request)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null) return Unauthorized();
        
        var userId = Guid.Parse(userIdClaim);
        var success = await _videoService.UpdateVideoAsync(id, userId, request);
        
        if (!success) return NotFound();
        return Ok();
    }
    
    [Authorize]
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteVideo(Guid id)
    {
        var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userIdClaim == null) return Unauthorized();
        
        var userId = Guid.Parse(userIdClaim);
        var success = await _videoService.DeleteVideoAsync(id, userId);
        
        if (!success) return NotFound();
        return Ok();
    }
}

// Form model for upload
public class VideoUploadRequest
{
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Category { get; set; } = string.Empty;
    public List<string>? Tags { get; set; }
    public IFormFile File { get; set; } = null!;
    public IFormFile? PreviewFile { get; set; }
}
